### ISSUE TITLE
First Draft Designs

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/LCN#16]
Hi @NB76,
I've been working on the first set of designs this morning and would love to get your initial feedback.
In particular I've focused on the flow of the staff answering anecdotal questions. 

1. This is how I imagine the home screen looking. With 4 clear options for the staff to choose from.  

![image](https://user-images.githubusercontent.com/26116988/33077431-bba400de-cec7-11e7-9aaa-c46a1062f793.png)

2. On selection of an option the user would be taken to a screen where they can write about the issue. 
We thought it might be nice for the user to have access to see other stories at this stage so they can get inspiration. They can do this by clicking on the tab. 
We also included the option for the user to remain anonymous if they do not feel comfortable sharing their comments (perhaps not necessary?)   
   
![image](https://user-images.githubusercontent.com/26116988/33077513-e9e296e0-cec7-11e7-8d3d-372175d317c9.png)

3. This is how we see the shared stories page looking.  
  
![image](https://user-images.githubusercontent.com/26116988/33077722-61378606-cec8-11e7-808e-710e2988dad8.png)

__Comments__
* We image the screens for success story, bug bear, question and training to all be the same. Is this what you had in mind? 
* We are still working on designs for the entry page, choice of primary work page, and the whole journey for the rep. 

__Feedback__
Please let us know your thoughts/questions/comments/etc. so we can work on altering the designs!

**Comment by Jen-Harris** [comment]
Here's one more! 
The choice of area: 
![image](https://user-images.githubusercontent.com/26116988/33088083-8046a2d6-cee4-11e7-813b-f678f6276c91.png)

**Comment by NB76** [comment]
Great first go, and nice to see it looking so good already! 

Here are my comments so far:

The screens for each of the four pathways don't have to look alike. It would be nice for the visuals in each to correspond to its theme. 

I think the 'success story' section would better be called 'made my day' or something similar. 'success story' or the trophy icon suggest competition for more lucrative legal wins, and what we want to elicit is not just that but stories of good practice, or personal proud moments, or just inspirational stories (e.g. refugee client coming in to see solicitor with her family after being helped to be reunited with them after years apart).

In a similar vein, a more informal, even playful approach would be better for the whole individual feedback section (not the rep/quant section). That way, rather than the purposeful 'what do you want to do today', how about something like 'How has my week been?' or the like.

Accessing other people's stories is definitely the right approach. This would also be where people could upvote/clap/star a story, or maybe also comment on it. No need for anonymity, though: we're a small network, and if you can't say something to someone openly, you had probably better keep it to yourself anyway.

**Comment by NB76** [comment]
On the 'one more', in line with my previous comments: retitle it "my main area of law". 

I would arrange the areas by row, so the most common ones: housing, WB, immigration and employment (add to it '/discrimination') would be first row; then debt, community care (add 'care'), public law and family; then the rest. 

For look and feel, please refer back to the Crazy Eights we had yesterday ( @m4v15 has them). They may be doodlings done on the hoof, but they reflect the kind of things people feel are salient, and a preference for a softer tone of voice. 

I think we also need two additional action options, besides the main four: call them 'snapshot' and 'I spy'. I-Spy will ask them 'what trends are you noticing locally that you would like us to know about?' or something to that effect (this was on the Crazy Eights). 

Snapshot will pull quant data from the rep interface to show people a - wait for it - snapshot of what comes through the door across the network. It would then ask them 'looks familiar? If not, tell us more!' linking to I-Spy so they can report what they think the dashboard does not reflect.

**Comment by Jen-Harris** [comment]
Morning @NB76. Thank you so much for such detailed feedback 👍 

There's just one thing we aren't certain about.  

_*"For look and feel, please refer back to the Crazy Eights we had yesterday ( @m4v15 has them). They may be doodlings done on the hoof, but they reflect the kind of things people feel are salient, and a preference for a softer tone of voice."*_

Can you be more specific on this point please? Is it mainly that you would like it to be more 'playful' design and with a softer tone of voice? We can send over pictures of the crazy 8's if this is helpful to refer to.

Please let us know as soon as possible so we can make the appropriate amends!

**Comment by NB76** [comment]
Thanks Jen, I've snapped the final Crazy Eights that we sat down with, so I have those.

You've got the gist of it. By tone of voice I meant the informal (but not overly chummy/patronising) tone of the questions and other text, and its reflection in the visuals. By salient things I mean the bits that people clearly felt should be in the designs: bugbears, successes, insights/trends/stories, being able to see the bigger picture, being able to ask LCN questions or make requests - all things we have included, thankfully. I just don't want us to lose sight of them when we move on to other bits, because these are the elements that seem to engage individuals most. 

The 'salient things' also refer to what people regard as more important to keep tabs on in the 'snapshot' dashboard: 
- trends at their LC/regionally/nationally (e.g. 'biggest problem seen this week')
- how many people seen/helped overall
- --of them how many new cases (ongoing) and how many one-off help
- --how many couldn't be helped so were signposted elsewhere
- --how many could not be signposted anywhere else because there is nothing else (growing problem)
- capacity flag (the 'too many cases' situation in which a LC operates at capacity)

So no amendments so far, just things to bear in mind for the next bit!

**Comment by Jen-Harris** [comment]
Thanks @NB76 

In terms of the 'snapshot' dashboard, would these all be at a weekly view or more longterm?

**Comment by NB76** [comment]
Let's start with weekly. That's what was entertained on Monday, and for the individual/qual pathway (not the rep/quant one) it's not too long to recap so people don't start forgetting things.

**Comment by Jen-Harris** [comment]
Thanks, 
two more questions re. design!

1. We've just spoken to @nogainbar and she feels that having 6 choices for the user is becoming too cluttered and may become a barrier to staff who are short on time to focus on tasks. 
As recommendation she suggested having 4 larger choices: I-spy, Snapshot, Bug Bear and Made my day. Then for the talk to LCN and Training we can provide a link at the bottom of the page for the staff to contact members of the LCN. 
Something like this:
![image](https://user-images.githubusercontent.com/26116988/33134680-453aa55c-cf98-11e7-81f5-368246b971b4.png)

What do you think? 

2. For the "Snapshot" section are you looking to compare the individual LC to the national averages? i.e. "in your LC there were 19 visitors this week. The national average was 28"  
_*Or*_ was it's purpose to only show the full national level stats? 
__*Or*__ something entirely different?

**Comment by NB76** [comment]
@nogainbar has a point, I've been thinking about that today as well. I reckon that 'Ask LCN' and 'training needs' can be merged into one, reflecting the two meanings of 'ask' (request and question). 

One treatment of this could be along the lines of your suggestion: text at the bottom, but make it centered and much more prominent: "Got a question? Got a request? ASK US!" 

Another treatment could be as another 'button' like the current four, but rearrange them as a flower (kinda): 'snapshot' (the only non-interactive choice) in the middle, and the other four arranged around it (also reminiscent of our logo, but that's more incidental than intentionally corny).

Also, could I ask that you round off the 'buttons' corners? A little more cuddly that way.

As for 'snapshot', good question! My original intention was your first option - to compare the Law Centre tally to the regional and national averages, e.g. "Harrow Law Centre has had to turn away 45 people last month. The London region average was 47, and the national average was 50." Possibly render it as a three-bar horizontal bar chart (local, regional, national).

Since we have the data anyway, it would be a nice motivator to have monthly cumulatives too: e.g. "Across the network, Law Centres have given 679 people one-off advice." The important one is the averages, and cumulatives is secondary. Let's see how that fares in testing!

**Comment by Jen-Harris** [comment]
Hey @NB76,
Thanks for this. 
I think we'll go for your first suggestion regarding asking LCN questions as timings are very tight. however, if we were to continue this project in the New Year your second option is certainly a design idea worth exploring. 

In terms of the Snapshot page, I think this is beginning to feel quite out of scope for the prototype phase. I think the best way to proceed with this will be to keep the choice in for users (for testing) and just say _*"Coming Soon"*_ on the snapshot page for the time being. 

I hope this OK?

**Comment by NB76** [comment]
Sure, @Jen-Harris. In snapshot, just for illustration, you could put a couple of random bar charts, just for illustration along the lines of my examples above.

**Comment by NB76** [comment]
Too many 'just for illustration's there. Writing this on the move. Sorry.
