### ISSUE TITLE
Questions for the reps

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/LCN#17]
Hi @NB76,
Do you have a view on what 'stats' questions you would like us to be asking the reps in the app?

**Comment by NB76** [comment]
I'll need to get back to you about the specific questions, but I would group them into several headings: 

CLIENTS - who is coming in: age/gender/ethnicity/marital status etc.

ASSISTANCE - figures on new enquiries, turn-aways, cases opened (most take months because they rely on interacting with public authorities, court hearings, etc. so you count new ones rather than closed ones), by type of service (local/outreach, in-house/pro bono etc.)

OUTCOMES - evictions prevented, appeals won, amount of money raised in additional benefits for clients etc.

Makes sense?

**Comment by Jen-Harris** [comment]
Thanks @NB76, this makes perfect sense. 
This is a good place for us to start. When do you think you'll be able to share the specific questions with us?

**Comment by NB76** [comment]
Hopefully tomorrow (Weds), more likely Thurs.

**Comment by NB76** [comment]
@Jen-Harris see below the questions for reps. 
[Scan of blank survey.pdf](https://github.com/InFact-coop/LCN/files/1499530/Scan.of.blank.survey.pdf)

This is the form that we get them to fill in once a year and too few do. Use it as a basis for the questions to reps, with the following changes: 
- All questions refer to the last calendar month (rather than year)
- Ignore question 2 - the focus of our exercise here is not how services are funded
- Ignore question 15

You will notice these only cover the categories CLIENTS and ASSISTANCE. I'd say let's start with those and add OUTCOMES later.

**Comment by Jen-Harris** [comment]
@NB76 I'm going to close this issue because as discussed we are focusing on the 'staff' journey as a priority
