### ISSUE TITLE
Setting up presentation meeting

### ISSUE THREAD

**Issue by NB76** [InFact-coop/LCN#65]
Hi all,
We have agreed to have the meeting to present and user-test this sprint's output next Friday. I want to line up diverse enough participants to attend (e.g. not just managers but caseworkers and receptionists) so, to echo Destiny's Child, QUESTION!
- Where would we like to have it? I can try and find a room here in Tavis House. If we know now there is no availability we can find somewhere else. 
- When would you like to have this - morning, lunchtime or afternoon? If flexible we can go by people's availability, which would be preferable
- For how long do we need people? 
- Is there any advance prep for them or for Julie and me?
Thanks,
Nimrod

**Comment by maxgerber** [comment]
Hi Nimrod @NB76,

 + Let's try and have it at Tavis House, though let us know if there isn't any space and we'll see what we can do.

 + Our availability is flexible - around 10:30am or 11:00am is usually good because it gives us time to set up, and plenty time to present the app, answer questions, and test it a bit

 + Regarding people... It'd probably be useful for you guys to be there for the whole thing! If you'd like to bring along a funder then we can kind of go through our process a bit first off, before presenting the app to you all, and then doing testing. Finally we'll have a chat about how the testing went, and how we might pivot the app in subsequent sprints based on these findings. The testers really only need to be around for the testing portion of the session - in fact they probably shouldn't be around for when we present the app, because we want them going in "blind", as it were. All in all I expect it will take around half a day - the same as the design workshop we had on Monday.

 + You supply the people, the copy throughout the sprint, and possibly the coffee. We can take care of the rest.

Regards,
Max

**Comment by NB76** [comment]
Tavis House is pretty much in the bag for Friday morning, I'm just waiting for formal confirmation from facilities. Alan (the funder) is unavailable that morning so it will just be us. If core participants start at 10:30, should we aim for users and testing at... 12 noon? 
NB

**Comment by maxgerber** [comment]
@NB76 I would actually say 11:30am should be sufficient, depending on if the funder comes or not

**Comment by NB76** [comment]
OK, users for testing at 11:30. The funder is definitely not coming, alas.

**Comment by maxgerber** [comment]
Ok Nimrod, so to confirm:

**Time**: 10:30am - 12:30pm, Friday 23rd February 2018
**Address**: Tavis House, 1-6 Tavistock Square, London WC1H 9NA
**People**: @NB76, Julie, @ivanmauricio, @nogainbar, @maxgerber

Sound good?

**Comment by NB76** [comment]
@nogainbar is coming, too? Cool! 
We will have the room from 10am to set up (*bring Mac adaptor!). 
From 10:30 we should also have Ruth, Sean and Shyam who were there last Monday. 
I have asked them to try and get caseworkers and/or receptionists to come in for user testing from 11:30.
